import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { handleRouteError, jsonError, parsePagination } from "@/lib/api";
import { requireCurrentUser, requireRole } from "@/lib/tenant";
import { isOrgRole } from "@/lib/types";

/**
 * GET /api/invites — Owner/Admin only. Lists invites for the caller's
 * server-resolved organization. Supports ?status= and pagination.
 */
export async function GET(request: NextRequest) {
  try {
    const membership = await requireRole(["owner", "admin"]);
    const { searchParams } = request.nextUrl;
    const { page, perPage, from, to } = parsePagination(searchParams);

    const supabase = await createClient();
    let query = supabase
      .from("invites")
      .select("id, email, role, status, expires_at, created_at", { count: "exact" })
      .eq("organization_id", membership.organization.id)
      .order("created_at", { ascending: false })
      .range(from, to);

    const status = searchParams.get("status");
    if (status) {
      if (!["pending", "accepted", "revoked", "expired"].includes(status)) {
        return jsonError("Invalid status filter.", 400);
      }
      query = query.eq("status", status);
    }

    const { data, error, count } = await query;
    if (error) {
      console.error("[api] invites list failed:", error);
      return jsonError("Could not load invites.", 400);
    }

    return NextResponse.json({
      data: data ?? [],
      pagination: { page, per_page: perPage, total: count ?? 0 },
    });
  } catch (error) {
    return handleRouteError(error);
  }
}

/**
 * POST /api/invites — Owner/Admin only. Creates an invite for the caller's own
 * organization; organization_id is server-resolved and any client-supplied
 * organization_id/token is ignored (the token is generated by the database).
 */
export async function POST(request: NextRequest) {
  try {
    const [membership, inviter] = await Promise.all([
      requireRole(["owner", "admin"]),
      requireCurrentUser(),
    ]);

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return jsonError("Invalid JSON body.", 400);
    }

    const payload = (body ?? {}) as Record<string, unknown>;
    const email = typeof payload.email === "string" ? payload.email.trim().toLowerCase() : "";
    const role = payload.role;

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return jsonError("Enter a valid email address.", 400);
    }
    if (!isOrgRole(role)) {
      return jsonError("Select a valid role.", 400);
    }
    // Only an Owner may mint another Owner — an Admin promoting someone to
    // Owner would be a privilege escalation.
    if (role === "owner" && membership.role !== "owner") {
      return jsonError("Only an Owner can invite another Owner.", 403);
    }

    const supabase = await createClient();

    // Block duplicate invites to the same address while one is still live.
    const { data: existing } = await supabase
      .from("invites")
      .select("id")
      .eq("organization_id", membership.organization.id)
      .eq("email", email)
      .eq("status", "pending")
      .gt("expires_at", new Date().toISOString())
      .maybeSingle();

    if (existing) {
      return jsonError("An invite for this email is already pending.", 409);
    }

    const { data, error } = await supabase
      .from("invites")
      .insert({
        organization_id: membership.organization.id,
        email,
        role,
        // Recorded for the audit trail Module 14 will read.
        invited_by: inviter.id,
      })
      .select("id, email, role, status, token, expires_at, created_at")
      .single();

    if (error) {
      console.error("[api] invite create failed:", error);
      return jsonError("Could not create the invite.", 400);
    }

    // The token is returned once, to the Owner/Admin who created it, so they
    // can share the link. Module 15 (Notifications) will email this instead.
    const origin = request.nextUrl.origin;
    return NextResponse.json(
      { data, invite_url: `${origin}/invite/${data.token}` },
      { status: 201 }
    );
  } catch (error) {
    return handleRouteError(error);
  }
}
