// =============================================================================
// Find-or-open a WhatsApp thread, and move it to the top of the inbox.
//
// Shared by the two directions, which is the whole reason it is its own file:
//
//   - lib/messaging/inbound.ts, when a candidate texts in (service-role client,
//     no session, because a stranger with a phone has no login);
//   - lib/communications/send.ts, when anything sends a candidate a WhatsApp
//     message (whichever client the caller already holds).
//
// WHY OUTBOUND MESSAGES JOIN A THREAD AT ALL. Without this, the inbox would show
// what candidates said to us and the replies typed in the inbox, but not the
// templated messages the product sent — an interview reminder, a rejection. A
// recruiter reading that thread would conclude nobody had told the candidate
// anything, which is the "false statement generated by true rows" failure mode
// this codebase already guards against elsewhere. One timeline or none.
//
// Takes the client as a parameter rather than building one. That is what lets
// the same function serve a session-bound page and a service-role webhook — and
// it is the reason the whatsapp_conversations INSERT policy exists: a recruiter
// sending the first WhatsApp to a candidate opens the thread through their own
// session, under RLS, not through the service role.
// =============================================================================
import type { CommsClient } from "@/lib/communications/send";
import { formatDbError } from "@/lib/supabase/errors";

export type Thread = { id: string; candidateId: string | null };

/**
 * The thread for this number, opening one if there is none.
 *
 * `candidateId` is who to attribute a NEW thread to; it never overwrites an
 * existing thread's candidate. Re-attributing a live conversation is a
 * deliberate act with its own route (the inbox's "Link to candidate"), not
 * something a send should do as a side effect.
 *
 * Returns null on failure rather than throwing. A thread is bookkeeping around a
 * message; failing to open one must never cost the message itself.
 */
export async function findOrOpenThread({
  client,
  organizationId,
  phoneNumber,
  candidateId = null,
}: {
  client: CommsClient;
  organizationId: string;
  /** Digits only, country code included. The column's CHECK accepts nothing else. */
  phoneNumber: string;
  candidateId?: string | null;
}): Promise<Thread | null> {
  if (!/^\d{7,15}$/.test(phoneNumber)) return null;

  const { data: found, error: findError } = await client
    .from("whatsapp_conversations")
    .select("id, candidate_id")
    .eq("organization_id", organizationId)
    .eq("phone_number", phoneNumber)
    .maybeSingle();

  if (findError) {
    console.error(`[messaging] thread read failed: ${formatDbError(findError)}`);
    return null;
  }

  if (found) {
    const row = found as { id: string; candidate_id: string | null };
    return { id: row.id, candidateId: row.candidate_id };
  }

  const { data: created, error: insertError } = await client
    .from("whatsapp_conversations")
    .insert({
      organization_id: organizationId,
      candidate_id: candidateId,
      phone_number: phoneNumber,
    })
    .select("id, candidate_id")
    .single();

  if (created) {
    const row = created as { id: string; candidate_id: string | null };
    return { id: row.id, candidateId: row.candidate_id };
  }

  /*
    23505 — the (organization_id, phone_number) unique constraint.

    Not an edge case: Meta delivers in batches and retries, and a stage change
    that fires two templates at once sends two messages to the same number in the
    same instant. The constraint is what makes concurrency safe; this branch is
    what makes it invisible. Re-read rather than retry — whoever won the race has
    already created exactly the row we wanted.
  */
  if (insertError?.code === "23505") {
    const { data: raced } = await client
      .from("whatsapp_conversations")
      .select("id, candidate_id")
      .eq("organization_id", organizationId)
      .eq("phone_number", phoneNumber)
      .maybeSingle();

    if (raced) {
      const row = raced as { id: string; candidate_id: string | null };
      return { id: row.id, candidateId: row.candidate_id };
    }
  }

  console.error(`[messaging] thread insert failed: ${formatDbError(insertError)}`);
  return null;
}

/**
 * Moves a thread to the top of the inbox and refreshes its preview.
 *
 * One SQL statement behind an RPC, because "read the unread count, add one,
 * write it back" loses a message whenever two arrive together — and Meta
 * delivers in batches, so they do. See the function's own comment in migration
 * 0041.
 *
 * Never throws and never reports upward: the message it describes is already
 * recorded, and a stale preview is not worth failing a send or inviting a
 * webhook redelivery over.
 */
export async function bumpThread({
  client,
  conversationId,
  organizationId,
  preview,
  messageAt,
  inbound,
  autoReplied = false,
}: {
  client: CommsClient;
  conversationId: string;
  organizationId: string;
  preview: string;
  messageAt: string;
  inbound: boolean;
  /**
   * 0042 — the newest message in this thread was the agent's.
   *
   * Denormalised here rather than looked up by the inbox, so a 200-thread list
   * can render "the AI handled this" without a latest-message query per row.
   * Written by the statement that already moves the thread, so there is nothing
   * to drift.
   */
  autoReplied?: boolean;
}): Promise<void> {
  const { error } = await client.rpc("bump_whatsapp_conversation", {
    p_conversation_id: conversationId,
    p_organization_id: organizationId,
    p_preview: preview,
    p_message_at: messageAt,
    p_inbound: inbound,
    p_auto_replied: autoReplied,
  });

  if (error) {
    console.error(`[messaging] thread bump failed: ${formatDbError(error)}`);
  }
}
