// =============================================================================
// The site origin, from inside a server component.
//
// A ROUTE HANDLER HAS request.nextUrl.origin. A page does not — it has no
// request object — so the public link on the job page has to be derived from
// the forwarded headers instead. Next 15 removed `request.ip` and friends for
// the same reason: these values come from the hosting layer now.
//
// APP_URL is the fallback, and it matters in exactly one place that is easy to
// forget: an email or a QR code generated by a background job has no request at
// all. A relative link would be useless in both.
// =============================================================================
import { headers } from "next/headers";

export async function requestOrigin(): Promise<string | null> {
  try {
    const list = await headers();

    const host = list.get("x-forwarded-host") ?? list.get("host");
    if (host) {
      const protocol =
        list.get("x-forwarded-proto") ?? (host.startsWith("localhost") ? "http" : "https");
      return `${protocol}://${host}`;
    }
  } catch {
    // headers() throws outside a request scope. Fall through to APP_URL.
  }

  const configured = process.env.APP_URL?.trim().replace(/\/+$/, "");
  return configured && configured.length > 0 ? configured : null;
}
