// =============================================================================
// Placeholder tokens for candidate messages.
//
// REUSES lib/hiring-stages/placeholders.ts RATHER THAN REDEFINING IT — the same
// {{group.field}} vocabulary, the same TOKEN_PATTERN, the same insertToken()
// caret handling, the same renderTemplate(). The spec is explicit about this
// ("reuse that exact component, don't rebuild it"), and there is a stronger
// reason than instruction-following: a second renderer would mean {{job.title}}
// could resolve differently in a message than in a screening script, and the
// difference would surface as a candidate being told something the call did not
// say.
//
// What this file adds is four tokens a screening script has no use for. They are
// added HERE rather than to the shared catalogue so the stage-script picker never
// offers a field it cannot fill — see the note above lookupFor() in
// placeholders.ts.
// =============================================================================
import {
  PLACEHOLDER_FIELDS,
  renderTemplate,
  splitTokens,
  type PlaceholderField,
  type PlaceholderValues,
} from "@/lib/hiring-stages/placeholders";
import { buildPlaceholderValues } from "@/lib/hiring-stages/values";
import type {
  ApplicationValueSource,
  CandidateValueSource,
  JobValueSource,
} from "@/lib/hiring-stages/values";
import { MODE_LABELS, type InterviewMode } from "@/lib/interviews/feedback";
// Type-only: events.ts imports nothing from here, so this cannot cycle.
import type { CommunicationEventKey } from "@/lib/communications/events";
import { formatDateTimeInZone } from "@/lib/time";

/** Message-only fields. Interview details, and who is writing. */
export const MESSAGE_ONLY_FIELDS: PlaceholderField[] = [
  {
    token: "interview.time",
    label: "Interview Time",
    group: "interview",
    sample: "Tue 24 Mar 2026, 2:00 pm",
  },
  { token: "interview.mode", label: "Interview Mode", group: "interview", sample: "Video" },
  {
    token: "interview.location",
    label: "Interview Location / Joining Details",
    group: "interview",
    sample: "Google Meet — link below",
  },
  {
    token: "interview.link",
    label: "Interview Joining Link",
    group: "interview",
    sample: "https://meet.google.com/abc-defg-hij",
  },
  {
    token: "organization.name",
    label: "Your Organization",
    group: "organization",
    sample: "Webbee Global",
  },
  {
    token: "recruiter.name",
    label: "Assigned Recruiter",
    group: "organization",
    sample: "Priya Rathor",
  },
  {
    token: "recruiter.email",
    label: "Recruiter Email",
    group: "organization",
    sample: "priya@webbeeglobal.com",
  },
  {
    /*
      OPTIONAL IN PRACTICE. `users` has no phone column, so this resolves only
      when a deployment populates one. renderMessage() renders a missing value as
      an em dash rather than dropping it, so a template using this reads as a
      missing detail rather than as a broken sentence — and the preview shows that
      before anything is sent.
    */
    token: "recruiter.phone",
    label: "Recruiter Phone",
    group: "organization",
    sample: "+91 98200 11223",
  },
  {
    /*
      Separate from interview.time, which carries date AND time in one string
      ("Tue 24 Mar 2026, 2:00 pm"). Both exist because a reminder usually wants
      one or the other, not the pair: "your interview is tomorrow at 2:00 pm"
      needs the time alone.
    */
    token: "interview.date",
    label: "Interview Date",
    group: "interview",
    sample: "Tue 24 Mar 2026",
  },
];

/**
 * Fields that only exist for the CANDIDATE and APPLICATION, added here rather
 * than to the shared stage-script catalogue.
 *
 * Same reasoning as MESSAGE_ONLY_FIELDS above: a screening script has no use for
 * a first name split out of a full name, and widening PLACEHOLDER_FIELDS would
 * offer these in the stage-script picker where some of them resolve differently.
 */
export const MESSAGE_CANDIDATE_FIELDS: PlaceholderField[] = [
  {
    /*
      A greeting field. "Hi Rahul," reads as written by a person; "Hi Rahul
      Sharma," reads as generated by a system, which is exactly the impression a
      candidate-facing message should avoid.
    */
    token: "candidate.first_name",
    label: "First Name",
    group: "candidate",
    sample: "Rahul",
  },
  {
    token: "candidate.phone",
    label: "Candidate Phone",
    group: "candidate",
    sample: "+91 98765 43210",
  },
  {
    token: "application.applied_date",
    label: "Application Date",
    group: "candidate",
    sample: "18 Mar 2026",
  },
];

/** The catalogue a message template may draw on. */
export const MESSAGE_PLACEHOLDER_FIELDS: PlaceholderField[] = [
  ...PLACEHOLDER_FIELDS,
  ...MESSAGE_CANDIDATE_FIELDS,
  ...MESSAGE_ONLY_FIELDS,
];

/**
 * The fields offered for a template attached to a PARTICULAR event.
 *
 * Interview fields are withheld unless the trigger is interview-related, and the
 * reason is the same one behind the whole closed-catalogue design: an offer letter
 * has no interview, so `{{interview.time}}` in a "Hired" template resolves to an
 * em dash in a sentence that reads as finished. Not offering it is the only
 * reliable way to stop that — a warning after the fact is read by nobody.
 *
 * The picker itself is unchanged. components/PlaceholderEditor already takes a
 * `fields` prop for exactly this purpose ("each caller passes the vocabulary that
 * is true where it renders"), so this is a narrower argument to the existing
 * component, not a second picker.
 */
export function messageFieldsForEvent(
  eventKey: CommunicationEventKey | null
): PlaceholderField[] {
  const interviewEvents: CommunicationEventKey[] = [
    "phone_interview_scheduled",
    "video_interview_scheduled",
    "director_round_scheduled",
    "interview_reminder",
    // A screening CALL is scheduled the same way and carries a time, so a
    // template for it legitimately wants the interview time fields.
    "ai_screening_call_scheduled",
  ];

  // No event chosen yet: offer everything rather than nothing. A picker that is
  // empty until an unrelated dropdown is set reads as broken.
  if (eventKey === null || interviewEvents.includes(eventKey)) {
    return MESSAGE_PLACEHOLDER_FIELDS;
  }

  return MESSAGE_PLACEHOLDER_FIELDS.filter((field) => field.group !== "interview");
}

/** Splits a message body's tokens into resolvable and not. */
export function splitMessageTokens(body: string) {
  return splitTokens(body, MESSAGE_PLACEHOLDER_FIELDS);
}

/** Renders a message body against real values. */
export function renderMessage(body: string, values: PlaceholderValues): string {
  return renderTemplate(body, values, {
    fields: MESSAGE_PLACEHOLDER_FIELDS,
    // A missing value renders as an em dash rather than vanishing.
    //
    // Deliberately different from a screening script, which drops it: a script
    // is read aloud by an agent that can improvise around a gap, but a written
    // message keeps its sentence structure. "Your interview is at ." reads as a
    // bug the candidate cannot resolve; "Your interview is at —." reads as a
    // missing detail they can ask about, and it is visible in the preview before
    // anything is sent.
    onMissing: "—",
  });
}

export type InterviewValueSource = {
  scheduled_at: string;
  mode: InterviewMode;
  location: string | null;
  meeting_url: string | null;
};

/**
 * Builds the substitution map for a message.
 *
 * Delegates the job/candidate/application half to Module 3's
 * buildPlaceholderValues() — the one mapping from columns to tokens — and adds
 * the message-only fields on top. Nothing here re-derives a value that function
 * already knows how to produce.
 *
 * `timeZone` is the ORGANIZATION's, never the server's: this string is the time a
 * candidate will turn up at, and a server in UTC would tell somebody in Gurgaon
 * to arrive five and a half hours early.
 */
export function buildMessageValues({
  job,
  candidate,
  application,
  interview,
  organizationName,
  recruiterName,
  timeZone,
}: {
  job?: JobValueSource | null;
  candidate?: CandidateValueSource | null;
  application?: ApplicationValueSource | null;
  interview?: InterviewValueSource | null;
  organizationName?: string | null;
  recruiterName?: string | null;
  timeZone: string;
}): PlaceholderValues {
  const values: PlaceholderValues = buildPlaceholderValues({ job, candidate, application });

  values["organization.name"] = organizationName ?? null;
  values["recruiter.name"] = recruiterName ?? null;

  if (interview) {
    values["interview.time"] = formatDateTimeInZone(interview.scheduled_at, timeZone);
    values["interview.mode"] = MODE_LABELS[interview.mode] ?? interview.mode;
    // A video interview's "location" is its joining link; an onsite one's is an
    // address. One token, so a single template covers both rather than needing
    // one per mode.
    values["interview.location"] =
      interview.location ?? interview.meeting_url ?? null;
    values["interview.link"] = interview.meeting_url ?? null;
  } else {
    values["interview.time"] = null;
    values["interview.mode"] = null;
    values["interview.location"] = null;
    values["interview.link"] = null;
  }

  return values;
}
